version: "3.7"
services:
  web:
    build:
      context: ./docker
    volumes:
      - .:/usr/local/payroll
    ports:
      - 8000:8000
    privileged: true
    entrypoint:
      - /usr/local/payroll/docker/entrypoint.sh
