# Generated by Django 3.1.7 on 2021-03-04 05:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileIDRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.IntegerField()),
                ("created_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("employee_id", models.IntegerField()),
            ],
            options={"ordering": ["employee_id", "-end_date"]},
        ),
        migrations.CreateModel(
            name="TimeReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField()),
                ("entry_date", models.DateField()),
                (
                    "job_group",
                    models.CharField(
                        choices=[("A", "Job Group A"), ("B", "Job Group B")],
                        max_length=1,
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
        ),
    ]
