# Generated by Django 3.1.7 on 2021-03-16 20:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="total_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        )
    ]
