# Generated by Django 3.1.7 on 2021-03-17 01:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_payroll_total_hours")]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="job_group",
            field=models.CharField(
                choices=[("A", "Job Group A"), ("B", "Job Group B")],
                default=None,
                max_length=1,
            ),
            preserve_default=False,
        )
    ]
